DROP DATABASE IF EXISTS link_manager;
CREATE DATABASE link_manager;
USE link_manager;

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	role ENUM('USER', 'ADMIN') DEFAULT 'USER',
	username VARCHAR(30) NOT NULL UNIQUE,
	password VARCHAR(60) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE links (
	id INT AUTO_INCREMENT PRIMARY KEY,
	creatorId INT NOT NULL,
	name VARCHAR(30) NOT NULL UNIQUE,
	description TEXT DEFAULT NULL,
	url TEXT NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	FOREIGN KEY(creatorId) REFERENCES users(id) 
);

CREATE TABLE link_assignments (
	userId INT,
	linkId INT,
	assignedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY(userId, linkId),
	FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(linkId) REFERENCES links(id) ON DELETE CASCADE ON UPDATE CASCADE
);